motd: '                &b&lREDE FANCY &8⚝ &7[1.8]\n              &6&lVENHA SE DIVERTIR!'

whitelist:
  motd: '                &b&lREDE FANCY &8⚝ &7[1.8]\n                  &c&lEM MANUTENÇÃO!'
  message: '§c§lREDE FANCY\n§c        Estamos em manutenção.'

unregister-commands:
  - '?'
  - 'help'
  - 'rl'
  - 'reload'
  - 'about'
  - 'pl'
  - 'plugins'
  - 'ver'
  - 'version'
  - 'me'
  - 'op'
  - 'fill'
  - 'clone'
  - 'kill'
  - 'say'
  - 'tellraw'
  - 'trigger'
  - 'list'
  - 'worldborder'
  - 'seed'
  - 'replaceitem'
  - 'setworldspawn'
  - 'scoreboard'
  - 'weather'
  - 'difficulty'
  - 'effect'
  - 'xp'
  - 'deop'
  - 'enchant'
  - 'ban'
  - 'ban-ip'
  - 'pardon'
  - 'pardon-ip'
  - 'setidletimeout'
  - 'give'
  - 'icanhasbukkit'
  - 'playsound'
  - 'restart'
  - 'testfor'
  - 'testforblock'
  - 'testforblocks'
  - 'title'
  - 'toggledownfall'
  - 'spreadplayers'